dist: trusty
language: node_js
node_js:
  - "10.15"

addons:
  chrome: stable

before_script:
  - npm install
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - npm run lint
  - npm run test
  - npm run test:coverage
